### ISSUE TITLE
Dependency bound issue

### ISSUE THREAD

**Issue by mniip** [jtdaugherty/vty-crossplatform#6]
`vty-crossplatform-0.1.0.0` build-depends on `vty >=6.0`, however it only builds with `vty-6.0`. Building with `vty >=6.1` fails with an error:
```
src/Graphics/Vty/CrossPlatform/Testing.hs:20:39: error: [GHC-83865]
    • Couldn't match type ‘Graphics.Vty.Config.VtyUserConfig’
                     with ‘Graphics.Vty.Platform.Unix.Settings.UnixSettings’
      Expected: Graphics.Vty.Platform.Unix.Settings.UnixSettings
                -> IO Output
        Actual: Graphics.Vty.Config.VtyUserConfig
                -> Graphics.Vty.Platform.Unix.Settings.UnixSettings -> IO Output
    • Probable cause: ‘buildOutput’ is applied to too few arguments
      In the second argument of ‘(>>=)’, namely ‘buildOutput’
      In the expression: defaultSettings >>= buildOutput
      In an equation for ‘mkDefaultOutput’:
          mkDefaultOutput = defaultSettings >>= buildOutput
   |
20 | mkDefaultOutput = defaultSettings >>= buildOutput
   |                                       ^^^^^^^^^^^
```
Please consider publishing a hackage revision for `vty-crossplatform-0.1.0.0` that excludes `vty >=6.1`

**Comment by jtdaugherty** [comment]
Thanks for reporting this! I've made the metadata update you requested. I would also encourage you to upgrade to more recent versions of the package if you can, since I can't promise that older versions will be supported.

**Comment by mniip** [comment]
> I would also encourage you to upgrade to more recent versions of the package if you can, since I can't promise that older versions will be supported.

I figure it's not supported (it's really rare to have more than one supported version), but its metadata on hackage is in some sense "supported for life".

Consider that hackage is trying to be a store of packages that is buildable forever, in the sense that if X depends on Y, and a new incompatible version of Y comes out, you can still build X because it has an upper bound telling cabal to not select the newest incompatible version of Y, but instead a sufficiently old one.

There are many ways of achieving this, see e.g. the four ways of the hackage trustees: https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md#best-practice-for-managing-meta-data

So if you upload a package version without upper bounds, you're sort of signing up for having to add the upper bounds at a later point whenever it breaks. Even if you have since moved on to newer versions of the package, the old version is still selectable, and so you have to retroactively fix it.

Of course, you the maintainer don't literally "have to", but hackage trustees will do it for you if you don't.

**Comment by jtdaugherty** [comment]
> Consider that hackage is trying to be a store of packages that is buildable forever

I can see how someone could take this point of view, and I understand that this is the context in which someone might run into a problem and ask for a metadata update. I'm happy to make occasional metadata updates, but I don't take the view that everything on Hackage implicitly needs to build forever, and I doubt many other maintainers take that view, either. The trustees can certainly do what helps them achieve their aims, though.

> So if you upload a package version without upper bounds, you're sort of signing up for having to add the upper bounds at a later point whenever it breaks

Yes, I'm aware of the consequence of not adding an upper bound. There are good reasons not to add upper bounds proactively, so there's a trade-off involved. I'm aware that not adding upper bounds sometimes means things will break, and the flip side is that adding upper bounds means I'll get much more reports of things not building when they probably should. Neither of those results in a user experience I'm excited about, though. I'm not saying I don't intend to add upper bounds; for many things I do, and sometimes I miss some or would rather set more relaxed bounds. But I mention this so you're aware that I'm familiar with the situation.
